---
repos:
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            args: [-l 120]
    - repo: local
      hooks:
          - id: commit-msg
            name: Commit Message Hook
            entry: ./hooks/commit-msg.sh
            language: script
            stages: [commit-msg]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      - id: check-yaml
        stages: [commit]
      - id: sort-simple-yaml
        stages: [commit]
      - id: end-of-file-fixer
      - id: trailing-whitespace


default_language_version:
    python: python3.10
