version: '2.2'
services:
  wg-manager:
    container_name: wg-manager
    build:
      context: ~/git/wireguard-manager/
      dockerfile: Dockerfile
    ports:
      - 6001:6000
    volumes:
      - ~/.ssh/:/opt/wireguard-manager/sshkeys
    restart: on-failure