version: '3.8'
services:
  wg-manager:
    container_name: wg-manager
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - UVICORN_HOST=wg-manager
      - UVICORN_PORT=5000
      - ENVIRONMENT=dev
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials
    restart: on-failure
    depends_on:
      - dynamodb-local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - 8000:8000
    user: root
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: [-jar, DynamoDBLocal.jar, -sharedDb, -dbPath, ./data]
volumes:
  dynamodb-data:
