version: '3.8'
services:
  wg-manager:
    container_name: wg-manager
    build:
      context: ~/git/wireguard-manager/
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - UVICORN_HOST=wg-manager
      - UVICORN_PORT=5000
    restart: on-failure
